# Generated by Django 6.0.2 on 2026-04-10 03:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('fonction', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.URLField(blank=True, max_length=500, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('PHARMACIE', 'Pharmacie'), ('REGION', 'Région'), ('NATIONAL', 'National')], max_length=20)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('photo', models.URLField(blank=True, max_length=500, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants', to='pharmacienatciapp.etablissement')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etablissements', to='pharmacienatciapp.region')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(max_length=100)),
                ('urgente', models.BooleanField(default=False)),
                ('progression', models.IntegerField(default=0)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_faites', to='pharmacienatciapp.etablissement')),
                ('fournisseur_etab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_recues', to='pharmacienatciapp.etablissement')),
            ],
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacienatciapp.etablissement'),
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('dci', models.CharField(max_length=255)),
                ('nomCommercial', models.CharField(max_length=255)),
                ('forme', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('codeATC', models.CharField(blank=True, max_length=50, null=True)),
                ('unite', models.CharField(max_length=50)),
                ('seuilMin', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seuilAlerte', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('laboratoire', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('prixUnitaire', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='pharmacienatciapp.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('numeroLot', models.CharField(max_length=100)),
                ('dateFabrication', models.DateField()),
                ('datePeremption', models.DateField()),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('expire', 'Expiré'), ('rappel', 'Rappel')], default='actif', max_length=10)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='pharmacienatciapp.fournisseur')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='pharmacienatciapp.medicament')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=15)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='pharmacienatciapp.commande')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacienatciapp.medicament')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeTransfert',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('quantiteDemandee', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantiteSatisfaite', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('statut', models.CharField(max_length=50)),
                ('dateDemande', models.DateTimeField(auto_now_add=True)),
                ('urgence', models.CharField(max_length=20)),
                ('etablissementCible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_transfert_recues', to='pharmacienatciapp.etablissement')),
                ('etablissementDemandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_transfert_emises', to='pharmacienatciapp.etablissement')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacienatciapp.medicament')),
            ],
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('typeMouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('DESTRUCTION', 'Destruction'), ('AJUSTEMENT', 'Ajustement')], max_length=20)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dateMouvement', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(max_length=100)),
                ('motif', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='valide', max_length=20)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacienatciapp.etablissement')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacienatciapp.lot')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacienatciapp.medicament')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lue', models.BooleanField(default=False)),
                ('destinataireUtilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destinataireRole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacienatciapp.role')),
            ],
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='role_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacienatciapp.role'),
        ),
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=15)),
                ('statut', models.CharField(max_length=50)),
                ('urgence', models.CharField(max_length=20)),
                ('dateTransfert', models.DateTimeField(auto_now_add=True)),
                ('demandeTransfert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacienatciapp.demandetransfert')),
                ('etablissementDestination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_recus', to='pharmacienatciapp.etablissement')),
                ('etablissementOrigine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_expedies', to='pharmacienatciapp.etablissement')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacienatciapp.medicament')),
            ],
        ),
    ]
