# Generated by Django — Retour and Prevision models

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacienatciapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retour',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=15)),
                ('motif', models.CharField(
                    choices=[
                        ('Avarie', 'Avarie'),
                        ('Non-conformité', 'Non-conformité'),
                        ('Péremption', 'Péremption'),
                        ('Rappel', 'Rappel'),
                    ],
                    max_length=50
                )),
                ('statut', models.CharField(
                    choices=[
                        ('En attente', 'En attente'),
                        ('Approuvé', 'Approuvé'),
                        ('Rejeté', 'Rejeté'),
                    ],
                    default='En attente',
                    max_length=20
                )),
                ('dateRetour', models.DateTimeField(auto_now_add=True)),
                ('etablissement', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='retours',
                    to='pharmacienatciapp.etablissement'
                )),
                ('lot', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='retours',
                    to='pharmacienatciapp.lot'
                )),
                ('medicament', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='retours',
                    to='pharmacienatciapp.medicament'
                )),
            ],
        ),
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('mois', models.CharField(max_length=10)),
                ('demandePrevue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('confiance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('facteurs', models.JSONField(blank=True, default=list)),
                ('medicament', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='previsions',
                    to='pharmacienatciapp.medicament'
                )),
            ],
        ),
    ]
