# Generated by Django 6.0.2 on 2026-04-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacienatciapp', '0002_retour_prevision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
