# Generated by Django 6.0.2 on 2026-04-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacienatciapp', '0003_alter_utilisateur_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='etablissements/'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medicaments/'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='utilisateurs/'),
        ),
    ]
