# Generated by Django 6.0.2 on 2026-04-11 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacienatciapp', '0004_alter_etablissement_photo_alter_medicament_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etablissements', to='pharmacienatciapp.region'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='unite',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True),
        ),
    ]
