# Generated by Django 6.0.2 on 2026-04-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacienatciapp', '0005_alter_etablissement_region_alter_medicament_unite'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='nom',
            field=models.CharField(default='Role', max_length=100),
        ),
    ]
