# Generated by Django 6.0.2 on 2026-04-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacienatciapp', '0006_role_description_role_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='notif_commande',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='notif_rupture',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='notif_systeme',
            field=models.BooleanField(default=False),
        ),
    ]
