# Generated by Django 6.0.2 on 2026-04-17 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacienatciapp', '0007_utilisateur_notif_commande_utilisateur_notif_rupture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saison',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('mois', models.JSONField(default=list)),
                ('actif', models.BooleanField(default=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saisons', to='pharmacienatciapp.region')),
            ],
        ),
    ]
