# Generated by Django 6.0.2 on 2026-04-17 18:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacienatciapp', '0008_saison'),
    ]

    operations = [
        migrations.AddField(
            model_name='prevision',
            name='dateFocalisation',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prevision',
            name='dateRuptureEstimee',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prevision',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previsions', to='pharmacienatciapp.etablissement'),
        ),
        migrations.AddField(
            model_name='prevision',
            name='etablissementSourceTransfert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previsions_source_transfert', to='pharmacienatciapp.etablissement'),
        ),
        migrations.AddField(
            model_name='prevision',
            name='niveau',
            field=models.CharField(choices=[('etablissement', 'Établissement'), ('region', 'Région')], default='etablissement', max_length=20),
        ),
        migrations.AddField(
            model_name='prevision',
            name='quantiteCommandeRecommandee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='prevision',
            name='recommandationCommande',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prevision',
            name='recommandationTransfert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prevision',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previsions', to='pharmacienatciapp.region'),
        ),
        migrations.AddField(
            model_name='prevision',
            name='risqueRupture',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prevision',
            name='stockActuelCalcule',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
