#!/usr/bin/env python3
"""
Generate a PostgreSQL import script for an existing Django-created schema.

Strategy:
  1. Disable FK triggers (session_replication_role = replica)
  2. Truncate all tables
  3. Temporarily cast boolean columns to smallint (so we can insert 0/1)
  4. INSERT all data from MySQL dump
  5. Cast smallint back to boolean
  6. Create/update sequences for auto-increment columns
  7. Re-enable FK triggers
"""

import re

INPUT = 'pharmacienatci.sql'
OUTPUT = 'import_data.sql'

# Tables in topological order (parents before children) for TRUNCATE
# (TRUNCATE ... CASCADE handles deps, but explicit order avoids issues)
TABLE_ORDER = [
    'pharmacienatciapp_utilisateur_user_permissions',
    'pharmacienatciapp_utilisateur_groups',
    'pharmacienatciapp_transfert',
    'pharmacienatciapp_retour',
    'pharmacienatciapp_prevision',
    'pharmacienatciapp_notification',
    'pharmacienatciapp_mouvement',
    'pharmacienatciapp_saison',
    'pharmacienatciapp_lot',
    'pharmacienatciapp_lignecommande',
    'pharmacienatciapp_demandetransfert',
    'pharmacienatciapp_commande',
    'pharmacienatciapp_medicament',
    'pharmacienatciapp_fournisseur',
    'pharmacienatciapp_categorie',
    'pharmacienatciapp_etablissement',
    'pharmacienatciapp_region',
    'pharmacienatciapp_role',
    'pharmacienatciapp_utilisateur',
    'django_admin_log',
    'django_session',
    'django_migrations',
    'django_content_type',
    'auth_group_permissions',
    'auth_permission',
    'auth_group',
]


def backtick_to_dquote(s):
    return re.sub(r'`(\w+)`', r'"\1"', s)


def main():
    with open(INPUT, encoding='utf-8') as f:
        lines = f.readlines()

    # --- Phase 1: collect tinyint(1) columns and auto-increment info ---
    bool_cols = {}   # table -> [col, ...]
    auto_inc = {}    # table -> (col, start_val_or_None)

    current_table = None
    in_create = False
    prev_alt = None

    for line in lines:
        s = line.rstrip('\n')

        # Detect CREATE TABLE
        m = re.match(r'CREATE TABLE `(\w+)`', s)
        if m:
            current_table = m.group(1)
            bool_cols[current_table] = []
            in_create = True
            prev_alt = None
            continue

        if in_create:
            m2 = re.match(r'\s+`(\w+)`\s+tinyint\(1\)', s)
            if m2:
                bool_cols[current_table].append(m2.group(1))
            if re.match(r'\) ENGINE=', s) or s.strip() == ');':
                in_create = False
            continue

        # Detect ALTER TABLE
        m = re.match(r'ALTER TABLE `(\w+)`', s)
        if m:
            prev_alt = m.group(1)
            continue

        # Detect MODIFY AUTO_INCREMENT
        if prev_alt:
            m2 = re.search(
                r'MODIFY `(\w+)` (?:int|bigint)\(\d+\) NOT NULL AUTO_INCREMENT(?:, AUTO_INCREMENT=(\d+))?',
                s
            )
            if m2:
                col = m2.group(1)
                start_val = int(m2.group(2)) if m2.group(2) else None
                auto_inc[prev_alt] = (col, start_val)
            if s.strip().endswith(';'):
                prev_alt = None

    # --- Phase 2: extract INSERT statements ---
    inserts = []
    i = 0
    n = len(lines)
    while i < n:
        s = lines[i].rstrip('\n')
        if re.match(r'INSERT INTO `', s):
            block = [backtick_to_dquote(s)]
            i += 1
            while i < n:
                val = lines[i].rstrip('\n')
                block.append(val)
                i += 1
                if val.rstrip().endswith(';'):
                    break
            inserts.append('\n'.join(block))
        else:
            i += 1

    # --- Phase 3: build the output SQL ---
    out = []

    out.append('-- PostgreSQL import script (data only, schema already created by Django)')
    out.append('-- Generated by generate_pg_import.py')
    out.append('')
    out.append('SET standard_conforming_strings = off;')
    out.append('SET escape_string_warning = off;')
    out.append('SET client_encoding = \'UTF8\';')
    out.append('')
    out.append('BEGIN;')
    out.append('')

    # Disable FK constraint triggers for faster import
    out.append('-- Disable FK constraint triggers')
    out.append("SET session_replication_role = 'replica';")
    out.append('')

    # Truncate all tables
    out.append('-- Truncate all tables')
    all_tables = list(bool_cols.keys())
    # Build the truncate list: use CASCADE to handle any FK deps
    tables_quoted = ', '.join(f'"{t}"' for t in TABLE_ORDER)
    out.append(f'TRUNCATE TABLE {tables_quoted} RESTART IDENTITY CASCADE;')
    out.append('')

    # Temporarily convert boolean columns to smallint
    bool_tables = {t: cols for t, cols in bool_cols.items() if cols}
    if bool_tables:
        out.append('-- Temporarily convert boolean columns to smallint for 0/1 data')
        for table, cols in bool_tables.items():
            for col in cols:
                out.append(
                    f'ALTER TABLE "{table}" ALTER COLUMN "{col}" TYPE smallint '
                    f'USING ("{col}"::integer);'
                )
        out.append('')

    # INSERT statements
    out.append('-- Data')
    for stmt in inserts:
        out.append(stmt)
        out.append('')

    # Convert smallint back to boolean
    if bool_tables:
        out.append('-- Restore boolean columns')
        for table, cols in bool_tables.items():
            for col in cols:
                out.append(
                    f'ALTER TABLE "{table}" ALTER COLUMN "{col}" TYPE boolean '
                    f'USING ("{col}" != 0);'
                )
        out.append('')

    # Update sequences
    if auto_inc:
        out.append('-- Update sequences')
        for table, (col, start_val) in auto_inc.items():
            if start_val:
                out.append(f"SELECT setval(pg_get_serial_sequence('\"{table}\"', '{col}'), {start_val}, false);")
            else:
                out.append(
                    f"SELECT setval(pg_get_serial_sequence('\"{table}\"', '{col}'), "
                    f"COALESCE((SELECT MAX(\"{col}\") FROM \"{table}\"), 0) + 1, false);"
                )
        out.append('')

    # Re-enable FK constraint triggers
    out.append('-- Re-enable FK constraint triggers')
    out.append("SET session_replication_role = 'origin';")
    out.append('')
    out.append('COMMIT;')

    with open(OUTPUT, 'w', encoding='utf-8') as f:
        f.write('\n'.join(out))

    print(f'Import script generated -> {OUTPUT}')
    print(f'  INSERT blocks:          {len(inserts)}')
    print(f'  Tables with bool cols:  {len(bool_tables)}')
    print(f'  Tables with sequences:  {len(auto_inc)}')


if __name__ == '__main__':
    main()
